// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yvvbdgxcmnztvezsayar.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl2dmJkZ3hjbW56dHZlenNheWFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDAzMjAsImV4cCI6MjA2MDYxNjMyMH0.MlqvIbStYqMdQRrVmNgq509G8HJHMmr5t1EbntpsGFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);